// Kompletna lista koparek BTC (SHA-256) z asicminervalue.com (2026-08-31).
// priceUsd: cena brutto z aktywnej oferty, chyba ze estimated:true
// (wtedy: interpolacja $/TH z podobnych pod wzgledem efektywnosci i skali modeli,
// bo strona nie miala aktywnej oferty dla tego modelu).
// priceUsd: null = brak wiarygodnej ceny (model wycofany / brak ofert) -> UI pokazuje "?".
//
// buyUrl: link do konkretnej oferty, w ktorej ta cena zostala zweryfikowana (2026-09-01).
// UI robi z ceny klikalny link, zeby dalo sie ja sprawdzic zamiast brac na wiare.
// Wpisuj buyUrl TYLKO gdy cena pochodzi z tej wlasnie strony — inaczej link klamie.
//
// UWAGA na interpolacje: dziala tylko dla zwyklych ASIC-ow sprzedawanych "za hashrate".
// Sprzet konsumencki (grzejniki 21energy/Heatbit, male minery hobbystyczne) ma cene
// urzadzenia AGD, nie cene za TH — interpolacja zaniza ja tam nawet 15x.
// Dla takich modeli wpisuj ceny recznie ze strony producenta (brutto, z VAT).
const MINERS_DATA_DATE = "2026-08-31";
const MINERS = [
  { name: "Bitaxe Ultra 1366", watts: 11, hashrateThs: 0.42, priceUsd: 114.99, buyUrl: "https://bitcoinmerch.com/products/bitcoin-merch-bitcoin-merch-bitaxe-1366-solo-bitcoin-miner-up-to-500gh-s" },
  { name: "Bitaxe Supra 401", watts: 14, hashrateThs: 0.6, priceUsd: 115, buyUrl: "https://apextomining.com/product/bitaxe-supra-401-solo-miner/" },
  { name: "Bitaxe Gamma 602", watts: 15, hashrateThs: 1.3, priceUsd: 129, buyUrl: "https://diglucky.com/products/bitaxe-gamma-601-bm1370-miner/" },
  { name: "Bitaxe Gamma 601", watts: 17, hashrateThs: 1.2, priceUsd: 69, buyUrl: "https://www.cryptominerbros.com/product/bitaxe-gamma-601-bitcoin-miner/" },
  { name: "Digital Shovel BluAx", watts: 18, hashrateThs: 1.2, priceUsd: 99 },
  { name: "Bitaxe Touch", watts: 22, hashrateThs: 1.6, priceUsd: 250, buyUrl: "https://www.solosatoshi.com/product/bitaxe-touch/" },
  { name: "Jingle Miner BTC Solo Lite", watts: 23, hashrateThs: 1.2, priceUsd: 99, buyUrl: "https://www.jinglemining.com/collections/jingle%20miner/products/jingle-miner-btc-solo-lite" },
  { name: "Heatbit Bitair", watts: 25, hashrateThs: 1.2, priceUsd: 179, buyUrl: "https://heatbit.com/" },
  { name: "Lucky Miner LV07", watts: 25, hashrateThs: 1, priceUsd: 129, buyUrl: "https://www.cryptominerbros.com/product/lucky-miner-lv07-bitcoin-miner/" },
  { name: "Bitaxe Gamma Duo 650", watts: 26, hashrateThs: 1.63, priceUsd: 104.29, buyUrl: "https://www.solosatoshi.com/product/bitaxe-duo-bitcoin-solo-miner-650-model/" },
  { name: "Bitaxe Gamma Turbo", watts: 35, hashrateThs: 2.4, priceUsd: 173.99, buyUrl: "https://www.solosatoshi.com/product/bitaxe-gt-gamma-turbo/" },
  { name: "BitForge BitForge Nano", watts: 35, hashrateThs: 2.4, priceUsd: 299.99, buyUrl: "https://bitcoinmerch.com/products/bitcoin-merch%C2%AE-bitforge-nano-2-6th-s-w-power-supply" },
  { name: "Braiins BMM100", watts: 40, hashrateThs: 1, priceUsd: null },
  { name: "Braiins BMM101", watts: 40, hashrateThs: 1, priceUsd: 299, buyUrl: "https://braiinsforge.com/products/bmm-101" },
  { name: "Hammer Miner Thor X1", watts: 46, hashrateThs: 3.22, priceUsd: 260, buyUrl: "https://www.cryptocloaks.com/product/hammer-miner-thor-x1-home-bitcoin-miner/" },
  { name: "Bitaxe Turbo Touch", watts: 48, hashrateThs: 2.67, priceUsd: 250, buyUrl: "https://www.solosatoshi.com/product/bitaxe-touch/" },
  { name: "Lucky Miner LV07 Pro", watts: 50, hashrateThs: 3, priceUsd: 199, buyUrl: "https://www.cryptominerbros.com/product/lucky-miner-lv07-pro-bitcoin-miner/" },
  { name: "NerdMiner NerdQaxe+", watts: 50, hashrateThs: 2.5, priceUsd: null },
  { name: "NerdMiner NerdQaxe+ Hydro", watts: 60, hashrateThs: 2.5, priceUsd: 489, buyUrl: "https://asicmarketplace.com/product/nerdminer-nerdqaxe-plus-hydro-bitcoin-miner/" },
  { name: "Bitaxe Supra Hex 701", watts: 75, hashrateThs: 4.2, priceUsd: 249, buyUrl: "https://asicmarketplace.com/product/bitaxe-supra-hex-701-bitcoin-miner/" },
  { name: "NerdMiner NerdQaxe++", watts: 76, hashrateThs: 4.8, priceUsd: 239, buyUrl: "https://www.cryptominerbros.com/product/nerdminer-nerdqaxe-plus-plus-bitcoin-miner/" },
  { name: "NerdMiner NerdQaxe++ Hydro", watts: 76, hashrateThs: 4.8, priceUsd: 168, buyUrl: "https://apextomining.com/product/nerdminer-nerdqaxe-plus-hydro-bitcoin-solo-miner/" },
  { name: "Jingle Miner BTC Solo Pro", watts: 96, hashrateThs: 4.8, priceUsd: 259, buyUrl: "https://www.jinglemining.com/collections/jingle%20miner/products/jingleminer-btc-solo-pro" },
  { name: "NerdMiner NerdQaxe++ Hydro Rev 6.1", watts: 103, hashrateThs: 6, priceUsd: 199, buyUrl: "https://apextomining.com/product/nerdqaxe-plus-plus-hydro-rev-6-1-bitcoin-solo-miner/" },
  { name: "NerdMiner NerdQaxe++ Rev 6.1", watts: 103, hashrateThs: 6, priceUsd: 289, buyUrl: "https://www.cryptominerbros.com/product/nerdminer-nerdqaxe-plus-plus-rev-6-1-bitcoin-miner/" },
  { name: "Lucky Miner LV08", watts: 120, hashrateThs: 4.5, priceUsd: 245, buyUrl: "https://www.woyouminer.com/product/lucky-miner-lv08-4-5t-btc-bitcoin-miner/" },
  { name: "Bitaxe Gamma Hex", watts: 140, hashrateThs: 8.4, priceUsd: 488, buyUrl: "https://xonmining.com/product/bitaxe-gamma-hex/" },
  { name: "Canaan Avalon Nano 3", watts: 140, hashrateThs: 4, priceUsd: 139, buyUrl: "https://www.jinglemining.com/collections/canaan/products/canaan-avalon-nano-3-4t" },
  { name: "Canaan Avalon Nano 3S", watts: 140, hashrateThs: 6, priceUsd: 289, buyUrl: "https://www.cryptominerbros.com/product/canaan-avalon-nano-3s-home-miner-6th-s/" },
  { name: "Lucky Miner LV08 Pro", watts: 150, hashrateThs: 7, priceUsd: 349, buyUrl: "https://www.cryptominerbros.com/product/lucky-miner-lv08-pro-bitcoin-miner/" },
  { name: "Hammer Miner Thor P2", watts: 155, hashrateThs: 10, priceUsd: 449, buyUrl: "https://www.cryptocloaks.com/product/hammer-miner-thor-p2-bitcoin-miner/" },
  { name: "NerdMiner NerdOCTAxe", watts: 160, hashrateThs: 9.6, priceUsd: 299, buyUrl: "https://asicmarketplace.com/product/nerdminer-nerdoctaxe-bitcoin-miner/" },
  { name: "NerdMiner NerdQX", watts: 170, hashrateThs: 8, priceUsd: 279, buyUrl: "https://www.cryptominerbros.com/product/nerdminer-nerdqx-bitcoin-miner/" },
  { name: "NerdMiner NerdOCTAxe Rev 3.1", watts: 240, hashrateThs: 12, priceUsd: 399, buyUrl: "https://asicmarketplace.com/product/nerdminer-nerdoctaxe-rev-3-1-bitcoin-miner/" },
  { name: "Bitmain Antminer S3", watts: 366, hashrateThs: 0.48, priceUsd: null },
  { name: "Heatbit Heatbit Trio", watts: 400, hashrateThs: 10, priceUsd: 849, buyUrl: "https://heatbit.com/products/heatbit-trio" },
  { name: "Bitmain Antminer S5", watts: 590, hashrateThs: 1.16, priceUsd: null },
  { name: "Bitmain Antminer S7-LN", watts: 697, hashrateThs: 2.7, priceUsd: null },
  { name: "Canaan Avalon Mini 3", watts: 800, hashrateThs: 37.5, priceUsd: null },
  { name: "Bitmain Antminer R4", watts: 845, hashrateThs: 8.7, priceUsd: null },
  { name: "21energy Ofen 2", watts: 1000, hashrateThs: 40, priceUsd: null },
  { name: "Pantech SX6", watts: 1000, hashrateThs: 8.5, priceUsd: null },
  { name: "Bitmain Antminer V9 (4Th)", watts: 1027, hashrateThs: 4, priceUsd: null },
  { name: "Ebang Ebit E9", watts: 1077, hashrateThs: 6.3, priceUsd: null },
  { name: "21energy Ofen 2 Pro", watts: 1100, hashrateThs: 60, priceUsd: null },
  { name: "Bitmain Antminer S9 (11.5Th)", watts: 1127, hashrateThs: 11.5, priceUsd: null },
  { name: "Canaan AvalonMiner 741", watts: 1150, hashrateThs: 7.3, priceUsd: null },
  { name: "Canaan AvalonMiner 821", watts: 1200, hashrateThs: 11.5, priceUsd: null },
  { name: "Bitmain Antminer S9 (12.5Th)", watts: 1225, hashrateThs: 12.5, priceUsd: null },
  { name: "Bitmain Antminer S9 SE (16Th)", watts: 1280, hashrateThs: 16, priceUsd: null },
  { name: "Bitmain Antminer S9i (13Th)", watts: 1290, hashrateThs: 13, priceUsd: null },
  { name: "Canaan AvalonMiner 841", watts: 1290, hashrateThs: 13.6, priceUsd: null },
  { name: "Bitmain Antminer S7", watts: 1293, hashrateThs: 4.73, priceUsd: null },
  { name: "Bitmain Antminer S9 (13Th)", watts: 1300, hashrateThs: 13, priceUsd: null },
  { name: "Ebang Ebit E9+", watts: 1300, hashrateThs: 9, priceUsd: null },
  { name: "Bitmain Antminer S9k (13.5Th)", watts: 1310, hashrateThs: 13.5, priceUsd: null },
  { name: "Bitmain Antminer S9i (14Th)", watts: 1320, hashrateThs: 14, priceUsd: null },
  { name: "Ebang Ebit E9.2", watts: 1320, hashrateThs: 12, priceUsd: null },
  { name: "Bitmain Antminer S9 (13.5Th)", watts: 1323, hashrateThs: 13.5, priceUsd: null },
  { name: "Bitmain Antminer S9j (14.5Th)", watts: 1350, hashrateThs: 14.5, priceUsd: null },
  { name: "Bitmain Antminer S9 (14Th)", watts: 1372, hashrateThs: 14, priceUsd: null },
  { name: "Bitfily Snow Panther B1", watts: 1380, hashrateThs: 16, priceUsd: null },
  { name: "Heatbit Heatbit", watts: 1400, hashrateThs: 14, priceUsd: null },
  { name: "Ebang Ebit E9i", watts: 1420, hashrateThs: 13.5, priceUsd: null },
  { name: "Bitmain Antminer T9+ (10.5Th)", watts: 1432, hashrateThs: 10.5, priceUsd: null },
  { name: "Bitmain Antminer T9 (11.5Th)", watts: 1450, hashrateThs: 11.5, priceUsd: null },
  { name: "Halong Mining DragonMint T1", watts: 1480, hashrateThs: 16, priceUsd: null },
  { name: "Bitmain Antminer S11 (20.5Th)", watts: 1530, hashrateThs: 20.5, priceUsd: null },
  { name: "Bitmain Antminer T15 (23Th)", watts: 1541, hashrateThs: 23, priceUsd: null },
  { name: "Innosilicon T2 Terminator", watts: 1570, hashrateThs: 17.2, priceUsd: null },
  { name: "Bitmain Antminer T9 (12.5Th)", watts: 1576, hashrateThs: 12.5, priceUsd: null },
  { name: "Bitmain Antminer S15 (28Th)", watts: 1596, hashrateThs: 28, priceUsd: null },
  { name: "Holic H22", watts: 1600, hashrateThs: 22, priceUsd: null },
  { name: "Ebang Ebit E10", watts: 1650, hashrateThs: 18, priceUsd: null },
  { name: "Canaan Avalon Q", watts: 1674, hashrateThs: 90, priceUsd: null },
  { name: "Canaan AvalonMiner 921", watts: 1700, hashrateThs: 20, priceUsd: null },
  { name: "Fluminer T3", watts: 1700, hashrateThs: 115, priceUsd: null },
  { name: "Bitmain Antminer S9 Hydro (18Th)", watts: 1728, hashrateThs: 18, priceUsd: null },
  { name: "Ebang Ebit E9.3", watts: 1760, hashrateThs: 16, priceUsd: null },
  { name: "MicroBT Whatsminer M21", watts: 1860, hashrateThs: 31, priceUsd: null },
  { name: "Ebang Ebit E11", watts: 1950, hashrateThs: 30, priceUsd: null },
  { name: "GMO miner B2", watts: 1950, hashrateThs: 24, priceUsd: null },
  { name: "Bitmain Antminer S17 Pro (50Th)", watts: 1975, hashrateThs: 50, priceUsd: null },
  { name: "Ebang Ebit E11++", watts: 1980, hashrateThs: 44, priceUsd: null },
  { name: "Innosilicon T2 Turbo", watts: 1980, hashrateThs: 24, priceUsd: null },
  { name: "MicroBT Whatsminer M3", watts: 2000, hashrateThs: 12, priceUsd: null },
  { name: "Ebang Ebit E11+", watts: 2035, hashrateThs: 37, priceUsd: null },
  { name: "Innosilicon T2 Turbo 25T", watts: 2050, hashrateThs: 25, priceUsd: null },
  { name: "MicroBT Whatsminer M3X", watts: 2050, hashrateThs: 12.5, priceUsd: null },
  { name: "Bitmain Antminer S17 Pro (53Th)", watts: 2094, hashrateThs: 53, priceUsd: null },
  { name: "Bitfily Snow Panther B1+", watts: 2100, hashrateThs: 24.5, priceUsd: null },
  { name: "Holic H28", watts: 2100, hashrateThs: 28, priceUsd: null },
  { name: "Innosilicon T2 Turbo 26T", watts: 2100, hashrateThs: 26, priceUsd: null },
  { name: "Innosilicon T3 43T", watts: 2100, hashrateThs: 43, priceUsd: null },
  { name: "StrongU STU-U8", watts: 2100, hashrateThs: 46, priceUsd: null },
  { name: "MicroBT Whatsminer M10", watts: 2145, hashrateThs: 33, priceUsd: null },
  { name: "Innosilicon T3 39T", watts: 2150, hashrateThs: 39, priceUsd: null },
  { name: "Aisen A1 Pro", watts: 2200, hashrateThs: 23, priceUsd: null },
  { name: "Bitmain Antminer T17 (40Th)", watts: 2200, hashrateThs: 40, priceUsd: null },
  { name: "Innosilicon T2 Turbo+ 32T", watts: 2200, hashrateThs: 32, priceUsd: null },
  { name: "Innosilicon T3+ 52T", watts: 2200, hashrateThs: 52, priceUsd: null },
  { name: "Canaan AvalonMiner 1047", watts: 2380, hashrateThs: 37, priceUsd: null },
  { name: "Bitmain Antminer S17 (53Th)", watts: 2385, hashrateThs: 53, priceUsd: null },
  { name: "Innosilicon T2 Turbo 29T/30T", watts: 2400, hashrateThs: 30, priceUsd: null },
  { name: "Ebang Ebit E12", watts: 2500, hashrateThs: 44, priceUsd: null },
  { name: "Ebang Ebit E12+", watts: 2500, hashrateThs: 50, priceUsd: 2449, buyUrl: "https://www.cryptominerbros.com/product/ebang-ebit-e12-50th-s-most-stable-bitcoin-miner/" },
  { name: "Bitmain Antminer S17 (56Th)", watts: 2520, hashrateThs: 56, priceUsd: 1650, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s17-56th-bitcoin-miner/" },
  { name: "Innosilicon T2 Turbo HF+", watts: 2600, hashrateThs: 33, priceUsd: null },
  { name: "Bitmain Antminer S19k Pro (120Th)", watts: 2760, hashrateThs: 120, priceUsd: 479, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s19k-pro/" },
  { name: "StrongU STU-U8 Pro", watts: 2800, hashrateThs: 60, priceUsd: null },
  { name: "Bitmain Antminer S19j Pro (96Th)", watts: 2832, hashrateThs: 96, priceUsd: null },
  { name: "Bitmain Antminer S17e (64Th)", watts: 2880, hashrateThs: 64, priceUsd: null },
  { name: "Bitmain Antminer T17e (53Th)", watts: 2915, hashrateThs: 53, priceUsd: null },
  { name: "Bitmain Antminer S17+ (73Th)", watts: 2920, hashrateThs: 73, priceUsd: 6249, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s17-73th-s-bitcoin-miner-sha-256-algorithm/" },
  { name: "iPollo B1L", watts: 3000, hashrateThs: 60, priceUsd: null },
  { name: "Bitmain Antminer S19 XP (140Th)", watts: 3010, hashrateThs: 140, priceUsd: 649, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s19-xp-140th-s/" },
  { name: "Bitmain Antminer S19j Pro (100Th)", watts: 3050, hashrateThs: 100, priceUsd: 1399, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s19j-pro-100th-s/" },
  { name: "Bitmain Antminer S19j Pro (104Th)", watts: 3068, hashrateThs: 104, priceUsd: 1199, buyUrl: "https://asicmarketplace.com/product/bitmain-antminer-s19j-pro-104th/" },
  { name: "Innosilicon T3 50T", watts: 3100, hashrateThs: 50, priceUsd: null },
  { name: "MicroBT WhatsMiner M70", watts: 3140, hashrateThs: 214, priceUsd: null },
  { name: "MicroBT WhatsMiner M70S", watts: 3140, hashrateThs: 226, priceUsd: 3399, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m70s-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M70S+", watts: 3140, hashrateThs: 244, priceUsd: null },
  { name: "Bitmain Antminer T19 (84Th)", watts: 3150, hashrateThs: 84, priceUsd: null },
  { name: "Bitmain Antminer T17+ (64Th)", watts: 3200, hashrateThs: 64, priceUsd: null },
  { name: "Canaan Avalon Made A1466", watts: 3230, hashrateThs: 150, priceUsd: 2699, buyUrl: "https://viperatech.com/product/canaan-avalonminer-a1466-150th-s-3230w" },
  { name: "Bitmain Antminer S19j XP (151Th)", watts: 3247, hashrateThs: 151, priceUsd: 1749, buyUrl: "https://asicmarketplace.com/product/bitmain-antminer-s19j-xp-151th/" },
  { name: "Bitmain Antminer S19 (95Th)", watts: 3250, hashrateThs: 95, priceUsd: null },
  { name: "Bitmain Antminer S19 Pro (110Th)", watts: 3250, hashrateThs: 110, priceUsd: null },
  { name: "Bitmain Antminer S19 Pro++", watts: 3250, hashrateThs: 125, priceUsd: null },
  { name: "Bitmain Antminer S19j (90Th)", watts: 3250, hashrateThs: 90, priceUsd: 1149, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s19j-90th-s/" },
  { name: "Canaan Avalon Made A1366", watts: 3250, hashrateThs: 130, priceUsd: null },
  { name: "Canaan AvalonMiner 1066", watts: 3250, hashrateThs: 50, priceUsd: null },
  { name: "MicroBT Whatsminer M30S", watts: 3268, hashrateThs: 86, priceUsd: 1749, buyUrl: "https://www.cryptominerbros.com/product/microbt-whatsminer-m30s-88th-s-bitcoin-miner/" },
  { name: "Canaan AvalonMiner 1146 Pro", watts: 3276, hashrateThs: 63, priceUsd: null },
  { name: "MicroBT Whatsminer M50S", watts: 3276, hashrateThs: 128, priceUsd: 759, buyUrl: "https://www.cryptominerbros.com/product/microbt-whatsminer-m50s-126th-s-bitcoin-miner/" },
  { name: "Bolon Miner B11", watts: 3300, hashrateThs: 70, priceUsd: null },
  { name: "Canaan Avalon Made A1346", watts: 3300, hashrateThs: 110, priceUsd: 1150, buyUrl: "https://aslminer.com/product/canaan-avalon-a1346/" },
  { name: "Innosilicon T3+ 57T", watts: 3300, hashrateThs: 57, priceUsd: null },
  { name: "MicroBT Whatsminer M50", watts: 3306, hashrateThs: 114, priceUsd: 1699, buyUrl: "https://www.cryptominerbros.com/product/microbt-whatsminer-m50-114th-s-bitcoin-miner/" },
  { name: "Canaan Avalon Made A1446", watts: 3310, hashrateThs: 135, priceUsd: 1750, buyUrl: "https://apextomining.com/product/canaan-avalon-asic-miner-1446-135t-3310w-blockchain-hardware-for-bitcoin-mining-btc-rig-on-sale/" },
  { name: "StrongU Hornbill H8", watts: 3330, hashrateThs: 74, priceUsd: null },
  { name: "Bitmain Antminer T19 (88Th)", watts: 3344, hashrateThs: 88, priceUsd: null },
  { name: "MicroBT Whatsminer M31S", watts: 3344, hashrateThs: 76, priceUsd: null },
  { name: "MicroBT Whatsminer M32", watts: 3348, hashrateThs: 62, priceUsd: null },
  { name: "Bitmain Antminer S19j Pro+ (122Th)", watts: 3355, hashrateThs: 122, priceUsd: null },
  { name: "MicroBT Whatsminer M20S", watts: 3360, hashrateThs: 68, priceUsd: null },
  { name: "MicroBT Whatsminer M21S", watts: 3360, hashrateThs: 56, priceUsd: 3200, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m21s-56th-s/" },
  { name: "MicroBT Whatsminer M31S+", watts: 3360, hashrateThs: 80, priceUsd: null },
  { name: "StrongU Hornbill H8 Pro", watts: 3360, hashrateThs: 84, priceUsd: null },
  { name: "Canaan AvalonMiner 1166 Pro", watts: 3400, hashrateThs: 81, priceUsd: null },
  { name: "MicroBT Whatsminer M30S+", watts: 3400, hashrateThs: 100, priceUsd: 460, buyUrl: "https://shop.whatsminer.com/products/details/50?lang=en-US" },
  { name: "GMO miner B3", watts: 3417, hashrateThs: 33, priceUsd: null },
  { name: "Bitmain Antminer T21 (180Th)", watts: 3420, hashrateThs: 180, priceUsd: null },
  { name: "Canaan Avalon A1566", watts: 3420, hashrateThs: 185, priceUsd: 2999, buyUrl: "https://www.cryptominerbros.com/product/canaan-avalon-a1566-bitcoin-miner/" },
  { name: "Canaan AvalonMiner 1126 Pro", watts: 3420, hashrateThs: 68, priceUsd: null },
  { name: "Canaan AvalonMiner 1246", watts: 3420, hashrateThs: 90, priceUsd: 1329, buyUrl: "https://asicmarketplace.com/product/canaan-avalon-miner-1246-85th/" },
  { name: "MicroBT WhatsMiner M60", watts: 3422, hashrateThs: 172, priceUsd: 1039, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m60-btc-miner/" },
  { name: "MicroBT Whatsminer M32S", watts: 3432, hashrateThs: 66, priceUsd: null },
  { name: "MicroBT WhatsMiner M60S", watts: 3441, hashrateThs: 186, priceUsd: 1799, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m60s-btc-miner/" },
  { name: "MicroBT Whatsminer M30S++", watts: 3472, hashrateThs: 112, priceUsd: null },
  { name: "Bitmain Antminer S23 (318Th)", watts: 3498, hashrateThs: 318, priceUsd: null },
  { name: "Bitmain Antminer S21 (200Th)", watts: 3500, hashrateThs: 200, priceUsd: 969, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-bitcoin-asic-miner/" },
  { name: "Ebang Ebit E10D", watts: 3500, hashrateThs: 25, priceUsd: null },
  { name: "MicroBT Whatsminer M10S", watts: 3500, hashrateThs: 55, priceUsd: null },
  { name: "Bitmain Antminer S21 Pro (234Th)", watts: 3510, hashrateThs: 234, priceUsd: 2009, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-pro-bitcoin-miner-234th-s/" },
  { name: "Bitmain Antminer S21+ (216Th)", watts: 3564, hashrateThs: 216, priceUsd: null },
  { name: "Canaan Avalon Miner A1366I", watts: 3570, hashrateThs: 119, priceUsd: 1050, buyUrl: "https://apextomining.com/product/avalon-hardware-a1366i-113t-119t-122t-3660w-bitcoin-profit-caculator-crypto-miner/" },
  { name: "MicroBT WhatsMiner M60S+", watts: 3600, hashrateThs: 212, priceUsd: 1739, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m60s-plus-btc-miner/" },
  { name: "MicroBT WhatsMiner M60S++", watts: 3600, hashrateThs: 226, priceUsd: 1850, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m60s-plus-plus-bitcoin-miner/" },
  { name: "Bitmain Antminer T21 (190Th)", watts: 3610, hashrateThs: 190, priceUsd: null },
  { name: "Bitdeer SealMiner A3 Pro Air", watts: 3625, hashrateThs: 290, priceUsd: 4899, buyUrl: "https://asicmarketplace.com/product/bitdeer-sealminer-a3-pro-air-bitcoin-miner/" },
  { name: "Bitdeer SealMiner A3 Air", watts: 3640, hashrateThs: 260, priceUsd: 4299, buyUrl: "https://asicmarketplace.com/product/bitdeer-sealminer-a3-air-bitcoin-miner/" },
  { name: "Bitmain Antminer S21 XP (270Th)", watts: 3645, hashrateThs: 270, priceUsd: 3789, buyUrl: "https://asicmarketplace.com/product/bitmain-antminer-s21-xp-bitcoin-miner/" },
  { name: "Canaan Avalon A15-194T", watts: 3647, hashrateThs: 194, priceUsd: 2710, buyUrl: "https://xonmining.com/product/canaan-avalon-a15-194t-3647w-bitcoin-miner/" },
  { name: "Bitdeer SealMiner A4 Pro Air", watts: 3662, hashrateThs: 336, priceUsd: 3335.9, buyUrl: "https://bitarkminer.com/product/bitdeer-sealminer-a4-pro-air-bitcoin-miner/" },
  { name: "Canaan Avalon A15Pro-218T", watts: 3662, hashrateThs: 218, priceUsd: 2615, buyUrl: "https://billionbison.com/products/canaan-avalon-a15pro-218t-1" },
  { name: "Canaan Avalon A15Pro-221T", watts: 3662, hashrateThs: 221, priceUsd: 1944.8, buyUrl: "https://shop.canaan.io/products/avalon-miner-a15pro" },
  { name: "Canaan Avalon A15XP-206T", watts: 3667, hashrateThs: 206, priceUsd: 3532.2, buyUrl: "https://oneminers.com/products/avalon-a15xp-206t-206-th-s" },
  { name: "Bitmain Antminer S21 Pro (245Th)", watts: 3675, hashrateThs: 245, priceUsd: 2119, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-pro-bitcoin-miner-234th-s/" },
  { name: "Bitmain Antminer S21+ (225Th)", watts: 3712, hashrateThs: 225, priceUsd: 1789, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-plus-bitcoin-miner/" },
  { name: "Bitdeer SealMiner A2", watts: 3730, hashrateThs: 226, priceUsd: 3749, buyUrl: "https://www.cryptominerbros.com/product/bitdeer-sealminer-a2-bitcoin-miner/" },
  { name: "Bitdeer SealMiner A2 Pro Air", watts: 3790, hashrateThs: 255, priceUsd: 3399, buyUrl: "https://www.cryptominerbros.com/product/bitdeer-sealminer-a2-pro-air-bitcoin-miner/" },
  { name: "Canaan Avalon A16XP-300T", watts: 3850, hashrateThs: 300, priceUsd: 4193, buyUrl: "https://apextomining.com/product/canaan-avalon-a16xp-bitcoin-miner/" },
  { name: "Bitmain Antminer S21+ (235Th)", watts: 3877, hashrateThs: 235, priceUsd: 2199, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-plus-bitcoin-miner/" },
  { name: "Canaan Avalon A16-282T", watts: 3900, hashrateThs: 282, priceUsd: 4199, buyUrl: "https://apextomining.com/product/canaan-avalon-a16-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M72S", watts: 4000, hashrateThs: 264, priceUsd: 3999, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m72s-bitcoin-miner/" },
  { name: "Bitmain Antminer S21 XP Immersion (300Th)", watts: 4050, hashrateThs: 300, priceUsd: 4179, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-xp-immersion-bitcoin-miner/" },
  { name: "Canaan Avalon A1566I", watts: 4500, hashrateThs: 261, priceUsd: null },
  { name: "Auradine Teraflux AT2880", watts: 4680, hashrateThs: 260, priceUsd: null },
  { name: "Bitmain Antminer S21+ Hyd (319Th)", watts: 4785, hashrateThs: 319, priceUsd: 3750, buyUrl: "https://millionminer.com/product/asic-miner/bitmain-antminer-s21-hyd-319th" },
  { name: "Bitmain Antminer S21e Hyd (288Th)", watts: 4896, hashrateThs: 288, priceUsd: 1498, buyUrl: "https://oneminers.com/products/bitmain-antminer-s21e-hyd-288-th-s" },
  { name: "Pantech WX6", watts: 5000, hashrateThs: 34, priceUsd: null },
  { name: "Bitmain Antminer T19 Pro Hyd (235Th)", watts: 5170, hashrateThs: 235, priceUsd: null },
  { name: "MicroBT WhatsMiner M76", watts: 5200, hashrateThs: 336, priceUsd: 4875, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m76-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M76S", watts: 5200, hashrateThs: 362, priceUsd: null },
  { name: "MicroBT WhatsMiner M76S+", watts: 5200, hashrateThs: 390, priceUsd: null },
  { name: "Bitmain Antminer S19 Pro Hyd (177Th)", watts: 5221, hashrateThs: 177, priceUsd: null },
  { name: "Bitmain Antminer S21e Hyd (310Th)", watts: 5270, hashrateThs: 310, priceUsd: 1499, buyUrl: "https://oneminers.com/products/antminer-s21e-hyd-310-th-s" },
  { name: "Bitmain Antminer S19 XP+ Hyd (279Th)", watts: 5301, hashrateThs: 279, priceUsd: 999, buyUrl: "https://oneminers.com/products/antminer-s19-xp-hyd-279-th-s" },
  { name: "Bitmain Antminer S23 Immersion (442Th)", watts: 5304, hashrateThs: 442, priceUsd: 10289, buyUrl: "https://oneminers.com/products/antminer-s23-immersion-442-th-s-batch-april-2026" },
  { name: "Bitmain Antminer S23 XP Hyd", watts: 5340, hashrateThs: 600, priceUsd: 15599, buyUrl: "https://asicmarketplace.com/product/bitmain-antminer-s23-xp-hydro-bitcoin-miner/" },
  { name: "Bitmain Antminer S19 XP Hyd (257Th)", watts: 5345, hashrateThs: 257, priceUsd: 1199, buyUrl: "https://oneminers.com/products/antminer-s19xp-hyd-257-th-s" },
  { name: "Bitmain Antminer S21 Hyd (335Th)", watts: 5360, hashrateThs: 335, priceUsd: null },
  { name: "Bitmain Antminer S21+ Hyd (358Th)", watts: 5370, hashrateThs: 358, priceUsd: 2299, buyUrl: "https://oneminers.com/products/antminer-s21-hyd-358-th-s" },
  { name: "Bitfily Snow Panther A1", watts: 5400, hashrateThs: 49, priceUsd: null },
  { name: "MicroBT WhatsMiner M66S+", watts: 5406, hashrateThs: 318, priceUsd: 2419, buyUrl: "https://oneminers.com/products/whatsminer-m66s-318-th-s-1" },
  { name: "Bitmain Antminer T19 Hydro (145Th)", watts: 5438, hashrateThs: 145, priceUsd: null },
  { name: "Bitmain Antminer S19 Pro+ Hyd (198Th)", watts: 5445, hashrateThs: 198, priceUsd: null },
  { name: "Bitmain Antminer S19 Hydro (158Th)", watts: 5451, hashrateThs: 158, priceUsd: null },
  { name: "Bitmain Antminer T19 Hydro (158Th)", watts: 5451, hashrateThs: 158, priceUsd: null },
  { name: "Bitmain Antminer S21 XP+ Hyd (500Th)", watts: 5500, hashrateThs: 500, priceUsd: null },
  { name: "Bitmain Antminer S23 Hyd (580Th)", watts: 5510, hashrateThs: 580, priceUsd: null },
  { name: "MicroBT WhatsMiner M66S", watts: 5513, hashrateThs: 298, priceUsd: null },
  { name: "MicroBT WhatsMiner M66S++", watts: 5518, hashrateThs: 356, priceUsd: null },
  { name: "MicroBT WhatsMiner M56", watts: 5550, hashrateThs: 194, priceUsd: null },
  { name: "MicroBT WhatsMiner M56S", watts: 5550, hashrateThs: 212, priceUsd: null },
  { name: "Bitmain Antminer S19 XP+ Hyd (293Th)", watts: 5567, hashrateThs: 293, priceUsd: null },
  { name: "Bitmain Antminer S21 Immersion (301Th)", watts: 5569, hashrateThs: 301, priceUsd: null },
  { name: "MicroBT WhatsMiner M66", watts: 5572, hashrateThs: 280, priceUsd: 1959, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m66-hydro-btc-miner/" },
  { name: "MicroBT Whatsminer M36S+", watts: 5576, hashrateThs: 164, priceUsd: null },
  { name: "Bitmain Antminer S21e XP Hyd (430Th)", watts: 5590, hashrateThs: 430, priceUsd: 4179, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21e-xp-hydro-bitcoin-miner/" },
  { name: "Bitmain Antminer S21 XP Hyd (473Th)", watts: 5676, hashrateThs: 473, priceUsd: 6629, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21-xp-hyd-bitcoin-miner/" },
  { name: "Bitmain Antminer S21j XP Hyd (495Th)", watts: 5940, hashrateThs: 495, priceUsd: 6579, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21j-xp-hydro-bitcoin-miner/" },
  { name: "Bitfury Tardis", watts: 6300, hashrateThs: 80, priceUsd: null },
  { name: "Bitfury B8", watts: 6400, hashrateThs: 49, priceUsd: null },
  { name: "MicroBT WhatsMiner M78S", watts: 6550, hashrateThs: 472, priceUsd: 6960, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m78s-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M63", watts: 6646, hashrateThs: 334, priceUsd: 2079, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m63-hydro-btc-miner/" },
  { name: "MicroBT Whatsminer M53", watts: 6670, hashrateThs: 230, priceUsd: null },
  { name: "Bitdeer SealMiner A3 Hydro", watts: 6750, hashrateThs: 500, priceUsd: 6750, buyUrl: "https://www.bitdeer.com/shop/product/P260104000001" },
  { name: "MicroBT Whatsminer M53S", watts: 6760, hashrateThs: 260, priceUsd: null },
  { name: "Auradine Teraflux AI3680", watts: 6840, hashrateThs: 360, priceUsd: 8888.88, buyUrl: "https://www.woyouminer.com/product/auradine-teraflux-ai3680-375t-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M63S++", watts: 7200, hashrateThs: 464, priceUsd: 4640, buyUrl: "https://shop.whatsminer.com/products/details/75?skuId=170" },
  { name: "MicroBT WhatsMiner M73", watts: 7200, hashrateThs: 470, priceUsd: 5589, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m73-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M73S", watts: 7200, hashrateThs: 500, priceUsd: 6689, buyUrl: "https://asicmarketplace.com/product/microbt-whatsminer-m73s-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M73S+", watts: 7200, hashrateThs: 540, priceUsd: 6995, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m73s-plus-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M63S+", watts: 7208, hashrateThs: 424, priceUsd: 5535, buyUrl: "https://oneminers.com/products/whatsminer-m63s-450-th-s" },
  { name: "MicroBT WhatsMiner M63S", watts: 7215, hashrateThs: 390, priceUsd: 3672, buyUrl: "https://shop.whatsminer.com/products/details/67?skuId=132" },
  { name: "MicroBT Whatsminer M33S++", watts: 7260, hashrateThs: 242, priceUsd: null },
  { name: "Bitdeer SealMiner A2 Hyd", watts: 7360, hashrateThs: 446, priceUsd: 6690, buyUrl: "https://www.bitdeer.com/shop/product/P241105000002" },
  { name: "Bitdeer SealMiner A4 Pro Hydro", watts: 7412, hashrateThs: 680, priceUsd: 8439, buyUrl: "https://apextomining.com/product/bitdeer-sealminer-a4-pro-hydro/" },
  { name: "Bitdeer SealMiner A2 Pro Hyd", watts: 7450, hashrateThs: 500, priceUsd: 6099, buyUrl: "https://www.cryptominerbros.com/product/bitdeer-sealminer-a2-pro-hydro-bitcoin-miner/" },
  { name: "Canaan Avalon A1566HA 2U", watts: 8064, hashrateThs: 480, priceUsd: 3398, buyUrl: "https://apextomining.com/product/canaan-avalon-a1566ha-2u-bitcoin-miner/" },
  { name: "Bitdeer SealMiner A3 Pro Hydro", watts: 8250, hashrateThs: 660, priceUsd: null },
  { name: "Bitdeer SealMiner A4 Ultra Hydro", watts: 8372, hashrateThs: 886, priceUsd: null },
  { name: "Bitmain Antminer S23e Hyd 2U (865Th)", watts: 8650, hashrateThs: 865, priceUsd: 9999, buyUrl: "https://asicmarketplace.com/product/bitmain-antminer-s23e-hydro-2u-bitcoin-miner/" },
  { name: "MicroBT WhatsMiner M6DS+", watts: 9200, hashrateThs: 540, priceUsd: 4000, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m6ds-plus-bitcoin-miner-hydro-cooling/" },
  { name: "MicroBT WhatsMiner M6DS++", watts: 9200, hashrateThs: 592, priceUsd: 4480, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m6ds-plus-plus-bitcoin-miner-hydro-cooling/" },
  { name: "MicroBT WhatsMiner M7D", watts: 9200, hashrateThs: 634, priceUsd: 5750, buyUrl: "https://apextomining.com/product/microbt-whatsminer-m7d-bitcoin-miner-hydro-cooling/" },
  { name: "MicroBT WhatsMiner M7DS", watts: 9200, hashrateThs: 680, priceUsd: 7599, buyUrl: "https://www.cryptominerbros.com/product/microbt-whatsminer-m7ds-bitcoin-miner/" },
  { name: "Bitmain Antminer S19 XP Hyd 3U", watts: 10600, hashrateThs: 512, priceUsd: 5573, buyUrl: "https://apextomining.com/product/bitmain-antminer-s19-xp-hyd-3u-bitcoin-miner-hydro-cooling/" },
  { name: "Auradine Teraflux AH3880", watts: 10740, hashrateThs: 600, priceUsd: 5699, buyUrl: "https://oneminers.com/products/auradine-teraflux-ah3880-600-th-s" },
  { name: "Bitmain Antminer S23 Hyd 3U", watts: 11020, hashrateThs: 1160, priceUsd: 28599, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s23-hydro-3u-bitcoin-miner/" },
  { name: "Bitmain Antminer S21e XP Hyd 3U", watts: 11180, hashrateThs: 860, priceUsd: 8279, buyUrl: "https://www.cryptominerbros.com/product/bitmain-antminer-s21e-xp-hydro-3u-bitcoin-miner/" },
  { name: "Proto Rig", watts: 12000, hashrateThs: 819, priceUsd: null },
  { name: "MicroBT WhatsMiner M79", watts: 14500, hashrateThs: 920, priceUsd: 13599, buyUrl: "https://minersmarket.ca/products/microbt-whatsminer-m79-920th-s" },
  { name: "MicroBT WhatsMiner M79S", watts: 20000, hashrateThs: 1350, priceUsd: 12289, buyUrl: "https://www.cryptominerbros.com/product/microbt-whatsminer-m79s-bitcoin-miner/" },
];
